package net.f708.realisticforging.utils;

public enum Animation {
    CANCEL,
    CLEANING,
    COOLING,
    PICKING,
    GRINDING,
    CUTTING,
    CARVING,
    SLEDGEHAMMERSWING,
    SLEDGEHAMMERSWINGSECOND,
    FORGINGUPSWING,
    FORGINGSWING,
    FORGINGHELPERUPSWING,
    FORGINGHELPERHOLDING,
    FORGINGHELPERDOWNSWING,
    CARVINGSTART,
    CARVINGHIT
}
